language: php
services:
  - docker

sudo: false

php:
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - docker-compose up -d
    - composer install
    - vendor/bin/console propel:install


script:
    - composer integrate
