language: php
services:
  - docker

sudo: false

php:
    - 7.3

env:
  YVES_HOST: localhost
  YVES_PORT: 8080

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - "php -S $YVES_HOST:$YVES_PORT -t tests/App/public/yves &"
    - docker-compose up -d
    - composer install
    - tests/App/bin/console transfer:generate
    - tests/App/bin/console propel:install

script:
    - composer integrate
