language: php
services:
  - docker

sudo: false

php:
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - "php -S 127.0.0.1:8086 &"
    - docker-compose up -d
    - composer install
    - tests/App/bin/console transfer:generate
    - tests/App/bin/console propel:install

script:
    - composer integrate
