language: php
services:
  - docker

sudo: false

php:
    - 7.2
    - 7.3

env:
  HOST_YVES: localhost
  PORT_YVES: 8085

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - "php -S $HOST_YVES:$PORT_YVES -t tests/App/public/yves &"
    - docker-compose up -d
    - composer install
    - tests/App/bin/console transfer:generate
    - tests/App/bin/console propel:install

script:
    - composer integrate
