version: "3"
services:
  postgres:
    image: "postgres:11"
    container_name: "my_postgres"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "54320:5432"

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - 16672:15672
      - 57720:5672
